name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and Push Docker image to Repository
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/demo-cicd:latest
            ${{secrets.DOCKERHUB_USERNAME}}/demo-cicd:${{ github.sha }}

      
      - name: Checkout Deployment Repository
        uses: actions/checkout@v4
        with:
          repository: sarubhai/demo_cd
          token: ${{ secrets.GH_PAT }}
          path: deploy-repo

      - name: Modify deployment.yml with the latest image
        working-directory: deploy-repo
        run: |
          # Remove Topics.csv from remote repo
          IMAGE_TAG="${{ secrets.DOCKERHUB_USERNAME }}/demo-cicd:${{ github.sha }}"
          sed -i "s|image:.*|image: ${IMAGE_TAG}|g" kubernetes/deployment.yaml

          # Commit changes to Deployment Repository
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          dt=$(date '+%Y-%m-%d')
          git add -A
          git commit -m "Automated Deployment- $dt"
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT }}
          path: deploy-repo
          branch: feature-new-deployment-config

      - name: Merge Pull Request
        working-directory: deploy-repo
        run: |
          git merge feature-new-deployment-config
          git push -u origin main
          git branch -d feature-new-deployment-config
          git push --delete origin feature-new-deployment-config
